version: "3.0"


services:
    backend:
        build: ./flask
        container_name: flask
        hostname: backend
        restart: always
        command: python app.py
        ports:
            - "7000:7000"
        networks:
            - default
        volumes:
            - "HostPath:/app/download" #download folder
            - "HostPath:/app/db" #db backup
    frontend:
        build: ./frontend
        hostname: frontend
        container_name: frontend
        restart: always
        ports:
            - "80:80"
        networks:
            - default
        depends_on:
            - backend